walmart/vista/cajero/urls.py
from django.contrib import admin
from django.urls import path, include
#from ui import urls
#from hook.urls import hook_patterns
#from ui.urls import ui_patterns
#from core.urls import core_patterns
from django.conf import settings
from django.conf.urls.static import static
from .router import router


urlpatterns = [
    #path('', include(hook_patterns)),
    #path('', include(urls.ui_patterns)),
    #path('', include(core_patterns)),
    path('', include('ui.urls')),
    path('api/', include(router.urls), name = 'models'),
    path('api/', include('api.urls'), name = 'views'),
    
    path('admin/', admin.site.urls),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

walmart/vista/ui/urls.py
from django.urls import path
from .views import UiPageView,UiCancelacionView,UiRecargaView

app_name = 'ui'
urlpatterns = [
    path('', UiPageView.as_view(), name='ui'),
    path('cancelacion/', UiCancelacionView.as_view(), name='cancelacion'),
    path('recarga/', UiRecargaView.as_view(), name='recarga'),
    
]

walmart/vista/ui2/urls.py
from django.urls import path
from .views import UiPageView


ui_patterns = ([
    path('', UiPageView.as_view(), name='ui'),
],"ui")

walmart/vista/ui/models.py
from django.db import models

# Create your models here.

walmart/vista/ui2/models.py
from django.db import models

# Create your models here.

walmart/vista/ui/views.py
from django.shortcuts import render,get_object_or_404
from django.views.generic.base import TemplateView,RedirectView

#import requests,json

from django.shortcuts import render, HttpResponse

# Create your views here.
cancelacion = 0

def home(request):
    return HttpResponse("<h1>PARKING TIP</h1><p>Estamos trabajando en el sitio</p>")

    
class UiPageView(TemplateView):
    template_name = "ui/ui.html"

class UiCancelacionView(TemplateView):
    template_name = "ui/ui.html"	
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['number'] = 3
        print("##########################")
        datos = {
        "cancelar_pago": 1,
        "operacion_recarga": 0,
        }
        url = 'http://127.0.0.1:8000/hook/'
        encabezado = {'Content-Type': 'application/json'}
        response = requests.post(
                url, data=json.dumps(datos),
                headers=encabezado
                )
        print("##########################",response.json())
        return context
class UiRecargaView(TemplateView):
    template_name = "ui/ui.html"	
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['number'] = 3
        print("##########################")
        datos = {
        "cancelar_pago": 0,
        "operacion_recarga": 1,
        }
        url = 'http://127.0.0.1:8000/hook/'
        encabezado = {'Content-Type': 'application/json'}
        response = requests.post(
                url, data=json.dumps(datos),
                headers=encabezado
                )
        print("##########################",response)
        #print("##########################",response.json())
        return context



class UiCounterRedirectView(RedirectView):

    permanent = False
    query_string = True
    pattern_name = 'article-detail'

    def get_redirect_url(self, *args, **kwargs):
        article = get_object_or_404(Article, pk=kwargs['pk'])
        article.update_counter()
        return super().get_redirect_url(*args, **kwargs)

walmart/vista/ui2/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView

# Create your views here.
class UiPageView(TemplateView):
    template_name = "ui/ui.html"	

walmart/vista/ui/templates/ui/ui.html
<!DOCTYPE html>
<html lang="es">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="colorlib.com">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Parking tip</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</head>

<body>


    <h1>PARKING TIP</h1>
    <p>
        Estamos construyendo el sitio
    </p>





</body>

</html>









<!-- <div id="tabs " class="tabs ">
        <div id="tab-1 " class="tab ">
            <input type="radio " id="tab-4 " name="tab-group-2 ">
            <label id="t1 " for="tab-4 ">Cajero</label>
            <div class="content ">
                <div class="container ">
                    <div class="row ">
                        <div class="col ">
                            <div class="card " style="width: 18rem; ">
                                <img src="{% static 'ui/images/services.png' %} " class="card-img-top " alt=" ">
                                <div class="card-body ">
                                    <h5 class="card-title ">Servicio</h5>
                                    <p class="card-text ">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                                    <a href="# " class="btn btn-primary ">Go somewhere</a>
                                </div>
                            </div>
                        </div>
                        <div class="col ">
                            <div class="vl "></div>
                            <div class="image image-bottom-right ">
                                <img src="{% static 'ui/images/insertar_ticket.gif' %} " alt=" " style="height:350px; ">
                                <p class="insert-ticket ">Inserte<br/>Ticket</p>
                                <p class="service ">Pago de <br/>Estacionamiento</p>
                            </div>
                        </div>


                    </div>

                    <div class="card card-upper ">
                        <img src="{% static 'ui/images/services.png' %} " alt=" ">
                        <h2 style="margin-top:45px ">Servicios</h2>
                    </div>
                    <div class="card card-middle ">
                        <img src="{% static 'ui/images/card.png' %} " alt=" ">
                        <h2 style="margin-top:25px ">Recarga de Tarjeta</h2>
                    </div>
                    <div class="card card-bottom ">
                        <img src="{% static 'ui/images/consulta.png' %} " alt=" " style="height:105px; float: left; margin-top:15px; margin-left:20px ">
                        <h2 style="margin-top:45px ">Consultar</h2>
                    </div>
                    <div class="vl "></div>
                    <div class="image image-bottom-right ">
                        <img src="{% static 'ui/images/insertar_ticket.gif' %} " alt=" " style="height:350px; ">
                        <p class="insert-ticket ">Inserte<br/>Ticket</p>
                        <p class="service ">Pago de <br/>Estacionamiento</p>
                    </div>
                    <div class="card-not-ticket ">
                        Sin Ticket
                    </div>
                    <a href="{% url 'ui:recarga' %} " class="link " style="color:red ">
                        Recarga/
                    </a>
                    <a href="/admin " class="link " style="color:red ">
                        Admin
                    </a>
                    <p class="date ">14:29, 23 de marzo de 2019</p>
                </div>
            </div>
        </div>
        <div id="tab-2 " class="tab ">
            <input type="radio " id="tab-5 " name="tab-group-2 ">
            <label for="tab-5 ">Cobro</label>
            <div class="content ">
                <div class="container ">
                    <div>
                        <img src="{% static 'ui/images/logo_transparent.png' %} " alt=" " style="height:150px; float: left ">
                    </div>
                    <table class="cobro ">
                        <tr>
                            <td class="cobro-td ">Ingreso</td>
                            <td id="hora_entrada " class="cobro-td ">14:20:00</td>
                        </tr>
                        <tr>
                            <td class="cobro-td ">Estancia</td>
                            <td id="tiempo_estacionado " class="cobro-td ">00:40:00</td>
                        </tr>
                        <tr>
                            <td class="cobro-td ">Descuento</td>
                            <td id="descuento " class="cobro-td ">$ 0.00</td>
                        </tr>
                    </table>
                    <table class="total-cobro ">
                        <tr class="total-cobro-tr ">
                            <td class="total-cobro-td ">Total</td>
                            <td id="monto_ingresar " class="total-td ">$ 20.00</td>
                        </tr>
                        <tr class="total-cobro-tr ">
                            <td class="total-cobro-td ">Ingresado</td>
                            <td id="monto_ingresado " class="ingresado-td ">$ 10.00</td>
                        </tr>
                    </table>
                    <div class="vl "></div>
                    <div class="image image-bottom-right ">
                        <img src="{% static 'ui/images/cajero-con-billete.gif' %} " alt=" " style="height:350px; ">
                        <p class="insert-ticket ">Inserte<br/>Dinero</p>
                        <p class="service ">Pago de <br/>Estacionamiento</p>
                    </div>

                    <a href="{% url 'ui:cancelacion' %} " class="link ">
                        <div class="panel-footer ">
                            <span class="pull-left "> Cancelar Pago</span>
                            <span class="pull-right "><i class="fa fa-arrow-circle-right "></i></span>
                            <div class="clearfix "></div>
                        </div>
                    </a>

                    <div id="monto_ingresado " class="card-not-ticket " }>
                        Cambio: 0
                    </div>
                    <p class="date ">14:29, 23 de marzo de 2019</p>
                </div>
            </div>
        </div>
        <div id="tab-3 " class="tab ">
            <input type="radio " id="tab-6 " name="tab-group-2 ">
            <label for="tab-6 ">Cobro</label>
            <div class="content ">
                <div class="container ">
                    <div>
                        <img src="{% static 'ui/images/logo_transparent.png' %} " alt=" " style="height:150px; float: left ">
                    </div>
                    <table class="cobro ">
                        <tr>
                            <td class="cobro-td ">Ingreso...</td>
                            <td id="hora_entrada " class="cobro-td ">14:20:00</td>
                        </tr>
                        <tr>
                            <td class="cobro-td ">Estancia...</td>
                            <td id="tiempo_estacionado " class="cobro-td ">00:40:00</td>
                        </tr>
                        <tr>
                            <td class="cobro-td ">Descuento...</td>
                            <td id="descuento " class="cobro-td ">$ 0.00</td>
                        </tr>
                    </table>
                    <table class="total-cobro ">
                        <tr class="total-cobro-tr ">
                            <td class="total-cobro-td ">Total...</td>
                            <td id="monto_ingresar " class="total-td ">$ 20.00</td>
                        </tr>
                        <tr class="total-cobro-tr ">
                            <td class="total-cobro-td ">Ingresado...</td>
                            <td id="monto_ingresado " class="ingresado-td ">$ 10.00</td>
                        </tr>
                    </table>
                    <div class="vl "></div>
                    <div class="image image-bottom-right ">
                        <img src="{% static 'ui/images/cajero-con-billete.gif' %} " alt=" " style="height:500px; ">
                        <p class="insert-ticket ">Inserte<br/>Dinero</p>
                        <p class="service ">Pago de <br/>Estacionamiento</p>
                    </div>

                    <a href="{% url 'ui:cancelacion' %} " class="link ">
                        <div class="panel-footer ">
                            <span class="pull-left "> Cancelar Pago</span>
                            <span class="pull-right "><i class="fa fa-arrow-circle-right "></i></span>
                            <div class="clearfix "></div>
                        </div>
                    </a>

                    <div id="monto_ingresado " class="card-not-ticket " }>
                        Cambio: 0
                    </div>
                    <p class="date ">14:29, 23 de marzo de 2019</p>
                </div>
            </div>
        </div> 
    </div> -->

walmart/vista/ui/templates/ui/ui_2.html
<!DOCTYPE html>
<html lang="es">

<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="colorlib.com">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="{% static 'ui/images/logo_transparent.png' %}" sizes="16x16">
    <title>EUM</title>
    <link rel="stylesheet" href="fonts/material-icon/css/material-design-iconic-font.min.css">
    <link rel="stylesheet" href="{% static 'ui/css/style.css' %}">
    <!--link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"-->
</head>

<body>
    <div id="tabs" class="tabs">
        <div id="tab-1" class="tab">
            <input type="radio" id="tab-4" name="tab-group-2">
            <label id="t1" for="tab-4">Cajero</label>
            <div class="content">
                <div class="container">
                    <div>
                        <img src="{% static 'ui/images/logo_transparent.png' %}" alt="" style="height:150px; float: left">
                    </div>
                    <div class="card card-upper">
                        <img src="{% static 'ui/images/services.png' %}" alt="" style="height:65px; float: left; margin-top:30px; margin-left:20px">
                        <h2 style="margin-top:45px">Servicios</h2>
                    </div>
                    <div class="card card-middle">
                        <img src="{% static 'ui/images/card.png' %}" alt="" style="height:105px; float: left; margin-top:10px; margin-left:20px">
                        <h2 style="margin-top:25px">Recarga de Tarjeta</h2>
                    </div>
                    <div class="card card-bottom">
                        <img src="{% static 'ui/images/consulta.png' %}" alt="" style="height:105px; float: left; margin-top:15px; margin-left:20px">
                        <h2 style="margin-top:45px">Consultar</h2>
                    </div>
                    <div class="vl"></div>
                    <div class="image image-bottom-right">
                        <img src="{% static 'ui/images/insertar_ticket.gif' %}" alt="" style="height:350px;">
                        <p class="insert-ticket">Inserte<br/>Ticket</p>
                        <p class="service">Pago de <br/>Estacionamiento</p>
                    </div>
                    <div class="card-not-ticket">
                        Sin Ticket
                    </div>
                    <a href="{% url 'ui:recarga' %}" class="link" style="color:red ">
                        Recarga/
                    </a>
                    <a href="/admin" class="link" style="color:red ">
                        Admin
                    </a>
                    <p class="date">14:29, 23 de marzo de 2019</p>
                </div>
            </div>
        </div>
        <div id="tab-2" class="tab">
            <input type="radio" id="tab-5" name="tab-group-2">
            <label for="tab-5">Cobro</label>
            <div class="content">
                <div class="container">
                    <div>
                        <img src="{% static 'ui/images/logo_transparent.png' %}" alt="" style="height:150px; float: left">
                    </div>
                    <table class="cobro">
                        <tr>
                            <td class="cobro-td">Ingreso</td>
                            <td id="hora_entrada" class="cobro-td">14:20:00</td>
                        </tr>
                        <tr>
                            <td class="cobro-td">Estancia</td>
                            <td id="tiempo_estacionado" class="cobro-td">00:40:00</td>
                        </tr>
                        <tr>
                            <td class="cobro-td">Descuento</td>
                            <td id="descuento" class="cobro-td">$ 0.00</td>
                        </tr>
                    </table>
                    <table class="total-cobro">
                        <tr class="total-cobro-tr">
                            <td class="total-cobro-td">Total</td>
                            <td id="monto_ingresar" class="total-td">$ 20.00</td>
                        </tr>
                        <tr class="total-cobro-tr">
                            <td class="total-cobro-td">Ingresado</td>
                            <td id="monto_ingresado" class="ingresado-td">$ 10.00</td>
                        </tr>
                    </table>
                    <div class="vl"></div>
                    <div class="image image-bottom-right">
                        <img src="{% static 'ui/images/cajero-con-billete.gif' %}" alt="" style="height:350px;">
                        <p class="insert-ticket">Inserte<br/>Dinero</p>
                        <p class="service">Pago de <br/>Estacionamiento</p>
                    </div>

                    <a href="{% url 'ui:cancelacion' %}" class="link">
                        <div class="panel-footer">
                            <span class="pull-left"> Cancelar Pago</span>
                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                            <div class="clearfix"></div>
                        </div>
                    </a>

                    <div id="monto_ingresado" class="card-not-ticket" }>
                        Cambio: 0
                    </div>
                    <p class="date ">14:29, 23 de marzo de 2019</p>
                </div>
            </div>
        </div>
        <div id="tab-3" class="tab">
            <input type="radio" id="tab-6" name="tab-group-2">
            <label for="tab-6">Cobro</label>
            <div class="content">
                <div class="container">
                    <div>
                        <img src="{% static 'ui/images/logo_transparent.png' %}" alt="" style="height:150px; float: left">
                    </div>
                    <table class="cobro">
                        <tr>
                            <td class="cobro-td">Ingreso...</td>
                            <td id="hora_entrada" class="cobro-td">14:20:00</td>
                        </tr>
                        <tr>
                            <td class="cobro-td">Estancia...</td>
                            <td id="tiempo_estacionado" class="cobro-td">00:40:00</td>
                        </tr>
                        <tr>
                            <td class="cobro-td">Descuento...</td>
                            <td id="descuento" class="cobro-td">$ 0.00</td>
                        </tr>
                    </table>
                    <table class="total-cobro">
                        <tr class="total-cobro-tr">
                            <td class="total-cobro-td">Total...</td>
                            <td id="monto_ingresar" class="total-td">$ 20.00</td>
                        </tr>
                        <tr class="total-cobro-tr">
                            <td class="total-cobro-td">Ingresado...</td>
                            <td id="monto_ingresado" class="ingresado-td">$ 10.00</td>
                        </tr>
                    </table>
                    <div class="vl"></div>
                    <div class="image image-bottom-right">
                        <img src="{% static 'ui/images/cajero-con-billete.gif' %}" alt="" style="height:500px;">
                        <p class="insert-ticket">Inserte<br/>Dinero</p>
                        <p class="service">Pago de <br/>Estacionamiento</p>
                    </div>

                    <a href="{% url 'ui:cancelacion' %}" class="link">
                        <div class="panel-footer">
                            <span class="pull-left"> Cancelar Pago</span>
                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                            <div class="clearfix"></div>
                        </div>
                    </a>

                    <div id="monto_ingresado" class="card-not-ticket" }>
                        Cambio: 0
                    </div>
                    <p class="date ">14:29, 23 de marzo de 2019</p>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'ui/vendor/jquery/jquery.min.js' %} "></script>
    <script src="{% static 'ui/vendor/jquery-validation/dist/jquery.validate.min.js' %} "></script>
    <script src="{% static 'ui/vendor/jquery-validation/dist/additional-methods.min.js' %} "></script>
    <script src="{% static 'ui/vendor/jquery-steps/jquery.steps.min.js' %} "></script>
    <script src="{% static 'ui/js/main.js' %} "></script>
    <script src="{% static 'ui/js/ws2.js' %} "></script>

</body>

</html>